// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_bomber_a");
	self attach("xmodel/c_br_head_bomber_copilot");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_bomber_a");
	precacheModel("xmodel/c_br_head_bomber_copilot");
}
