// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_bomber_parachute");
	self attach("xmodel/c_br_head_bomber_waistgunnerA");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_bomber_parachute");
	precacheModel("xmodel/c_br_head_bomber_waistgunnerA");
}
