// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_ingram");
	self attach("xmodel/c_br_head_ingram");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_ingram");
	precacheModel("xmodel/c_br_head_ingram");
}
