// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_shirt");
	self attach("xmodel/c_br_head_scar");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_shirt");
	precacheModel("xmodel/c_br_head_scar");
}
