// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_jerkin");
	self attach("xmodel/c_br_head_stash");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_jerkin");
	precacheModel("xmodel/c_br_head_stash");
}
