// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_ge_bod_tropical");
	character\_utility::attachFromArray(xmodelalias\head_axis::main());
	self.hatModel = "xmodel/c_ge_helmet_tropical";
	self attach(self.hatModel);
	self.voice = "german";
}

precache()
{
	precacheModel("xmodel/c_ge_bod_tropical");
	character\_utility::precacheModelArray(xmodelalias\head_axis::main());
	precacheModel("xmodel/c_ge_helmet_tropical");
}
