// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_resist_moe");
	self attach("xmodel/c_br_head_resist_moe");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_resist_moe");
	precacheModel("xmodel/c_br_head_resist_moe");
}
