// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_resist_tom");
	self attach("xmodel/c_br_head_resist_tom");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_resist_tom");
	precacheModel("xmodel/c_br_head_resist_tom");
}
