// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_br_body_resist_fat");
	self attach("xmodel/c_br_head_resist_fat");
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/c_br_body_resist_fat");
	precacheModel("xmodel/c_br_head_resist_fat");
}
