// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/c_rs_body_miesha_radio");
	self attach("xmodel/basehead_a_10");
	self.hatModel = "xmodel/sovietequipment_helmet";
	self attach(self.hatModel);
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/c_rs_body_miesha_radio");
	precacheModel("xmodel/basehead_a_10");
	precacheModel("xmodel/sovietequipment_helmet");
}
