// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_pavlov");
	self attach("xmodel/head_Pavlov");
	self.hatModel = "xmodel/sovietequipment_helmet";
	self attach(self.hatModel);
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/character_pavlov");
	precacheModel("xmodel/head_Pavlov");
	precacheModel("xmodel/sovietequipment_helmet");
}
