(add-classpath "file:///c:/projects/compojure/compojure.jar")
(add-classpath "file:///c:/projects/compojure/deps/commons-codec-1.3.jar")
(add-classpath "file:///c:/projects/compojure/deps/commons-fileupload-1.2.1.jar")
(add-classpath "file:///c:/projects/compojure/deps/commons-io-1.4.jar")
(add-classpath "file:///c:/projects/compojure/deps/grizzly-http-servlet-1.9.10.jar")
(add-classpath "file:///c:/projects/compojure/deps/grizzly-http-webserver-1.9.10.jar")
(add-classpath "file:///c:/projects/compojure/deps/jetty-6.1.15.jar")
(add-classpath "file:///c:/projects/compojure/deps/jetty-util-6.1.15.jar")
(add-classpath "file:///c:/projects/compojure/deps/servlet-api-2.5-20081211.jar")

(add-classpath "file:///c:/projects/codParser/")
(load-file "c:/Projects/codParser/test.clj")

;(def p-data (parse-log "C:/Projects/codParser/short-log.log"))
;(def dk-seq (get-log-type p-data damage-kill?))